### ISSUE TITLE
Add Search

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/tmdl-grass-swale-map#23]
Have a way to search or filter the points.

**Comment by talllguy** [comment]
[This looks promising](https://www.mapbox.com/mapbox.js/example/v1.0.0/filtering/)

**Comment by taojun545** [comment]
I designed a new interface:
![1](https://cloud.githubusercontent.com/assets/3824842/15078416/2253a0fe-1381-11e6-970a-2f6ec52d7647.png)

![2](https://cloud.githubusercontent.com/assets/3824842/15078418/242e0bee-1381-11e6-82e0-0d35b8006653.png)

**Comment by talllguy** [comment]
@taojun545 this is awesome and unexpected! Can you PR this? I'd like to test it.

**Comment by taojun545** [comment]
It seems I don't have permission to do that. Could you assign the permission?

**Comment by talllguy** [comment]
Just added you as a collaborator with Write access

**Comment by taojun545** [comment]
Done. Please check PR!

**Comment by talllguy** [comment]
fixed by #29
