### ISSUE TITLE
New midpoint data (Test)

### ISSUE THREAD

**Issue by cmolivi** [kcigeospatial/tmdl-grass-swale-map#33]
New data is in usual location...

FC: "MidPoints_Master_20160512"

**Comment by cmolivi** [comment]
New data is in usual location to reflect progress made...

FC: "MidPoints_Master_20160516"

**Comment by talllguy** [comment]
@cmolivi for that [last comment](https://github.com/kcigeospatial/tmdl-grass-swale-map/issues/33#issuecomment-219572951), please open that one as a new issue. Thanks!
