### ISSUE TITLE
Filter does not work from secure origin

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/tmdl-grass-swale-map#43]
@taojun545 Maybe you have an idea here.

I noticed the Chrome made a change where HTTPS is required to use the device geolocation function. When in the HTTPS version of the page, the filter does not work (filter by swales that are done).

**Comment by taojun545** [comment]
When using HTTPS, all the included links should use "https://..."
`<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>`
`<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>`

**Comment by talllguy** [comment]
@taojun545 thanks, should we force https? Know any good redirect scripts?

**Comment by taojun545** [comment]
Yes, I think we need to force the https if it is available.

You can put below code at https://github.com/kcigeospatial/tmdl-grass-swale-map/blob/master/index.html#L98

`if (window.location.protocol != "https:")
    window.location.href = "https:" + window.location.href.substring(window.location.protocol.length);`
