### ISSUE TITLE
Add a Waze directions button

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/tmdl-grass-swale-map#55]
This is [possible](https://www.waze.com/about/dev), but if the device doesn't have Waze (like a PC) what then?

**Comment by taojun545** [comment]
I added a Waze directions button, and it works on my iPhone. #59 

We can add some logic to identify the device, then show/hide the Waze Button.

**Comment by talllguy** [comment]
That'd be sweet! I think that'd be useful for any desktop users, that way they wouldn't see the button.

--
Elliott Plack
Business Analyst

KCI TECHNOLOGIES INC.
936 Ridgebrook Rd
Sparks, MD 21152
elliott.plack@kci.com<mailto:elliott.plack@kci.com>
o: 410.891.1750 | m: 410.206.6448
www.kci.com<http://www.kci.com>

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Mon, Jun 20, 2016 at 6:51 PM -0400, "Jun Tao" <notifications@github.com<mailto:notifications@github.com>> wrote:


I added a Waze directions button, and it works on my iPhone. #59<https://github.com/kcigeospatial/tmdl-grass-swale-map/pull/59>

We can add some logic to identify the device, then show/hide the Waze Button.

**Comment by taojun545** [comment]
New PR #61. Only show the button in iOS device.
