### ISSUE TITLE
Update Revisits in Source

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/tmdl-grass-swale-map#74]
Per [comment](https://github.com/kcigeospatial/tmdl-grass-swale-map/issues/73#issuecomment-232023503) by @cmolivi, there are some revisits that are actually down. I'll share them all here, then we can update.

**Comment by talllguy** [comment]
I remember this one being resolved for sure. 
![image](https://cloud.githubusercontent.com/assets/1827881/16766321/6cfcef88-4807-11e6-86d7-466de5084f71.png)

**Comment by talllguy** [comment]
That's all I can be sure of from memory. If you can give me a list of others I would have revisited in the past (it's been a while now), I can tell you the status.

**Comment by cmolivi** [comment]
Thanks re: Ind16_84, resolved in today's data. Typos also corrected.

List of old (possibly resolved) revisits:
Category_2A_479_Ind3_10
Category_2A_234_Ind31_10

**Comment by cmolivi** [comment]
Screenshots of said revisits:

![image](https://cloud.githubusercontent.com/assets/18336783/16767563/0fb330a6-480e-11e6-953b-b710a8e2f5fb.png)

![image](https://cloud.githubusercontent.com/assets/18336783/16767614/45ed3856-480e-11e6-85cc-a106fa2bbd48.png)

**Comment by talllguy** [comment]
OK, so for the one on Taneytown, that was under construction when we went out there the first time. I think the widened road erased the swale.

I don't think I worked on that one in the center of the interchange.

**Comment by cmolivi** [comment]
@talllguy great, edits done
