### ISSUE TITLE
color for mot / revisit

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/tmdl-grass-swale-map#76]
Since these are the same, we should come up with a better color scheme. Maybe yellow for revisit?

**Comment by cmolivi** [comment]
Yes I agree, yellow for Revisits.

**Comment by talllguy** [comment]
![image](https://cloud.githubusercontent.com/assets/1827881/16840956/329197dc-49a5-11e6-955c-79d27d6bc552.png)
Awesome, let's go with #f1f075

@cmolivi switch the above color hex for the revisits in future exports.

**Comment by cmolivi** [comment]
@talllguy great, will do. Thanks!
